### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Kepler7894i** [Kepler7894i/triangle-calculator#11]
This program needs to be properly tested as it is maintained to ensure that there are no bugs or errors

**Comment by mamadou-diallo** [comment]
Please let me help with this

**Comment by Kepler7894i** [comment]
I was going to when I got round to it this was more of a note but if you want to the help would be appreciated.
If you want you can help by entering in examples for it to calculate through the exe,predicting what should happen by calculating it yourself and then comparing this to the actual output of the program, if you find any errors then you can create an issue here and I'll try to fix it.

**Comment by Kepler7894i** [comment]
> 
> 
> Please let me help with this

I didn't think anyone would want to but if you want to the help it would be greatly appreciated.
If you want you can help by entering in examples for it to calculate through the exe (using the program on main branch not the program in development branch), predicting what should happen by calculating it yourself and then comparing this to the actual output of the program, if you find any errors then you can create an issue here and I'll try to fix it.

**Comment by Kepler7894i** [comment]
Main bulk of testing done, thanks for your help mamadou-diallo, any further testing can be helped by the fileInput() function added in a recent release.

**Comment by mamadou-diallo** [comment]
It was my pleasure to work with you

**Comment by Kepler7894i** [comment]
Likewise, thank you.
